"""add unique constraint to timestamp

Revision ID: 0e5e9e4a570d
Revises: cf3db07e76cf
Create Date: 2026-01-15 17:16:14.656073

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0e5e9e4a570d"
down_revision: Union[str, Sequence[str], None] = "cf3db07e76cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("weather") as batch_op:
        batch_op.create_unique_constraint("timestamp_is_unique", ["timestamp"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("weather") as batch_op:
        batch_op.drop_constraint("timestamp_is_unique", type_="unique")
    # ### end Alembic commands ###
